### ISSUE TITLE
How the code works

### ISSUE THREAD

**Issue by micBona** [ihormelnyk/arduino_opentherm_controller#3]
Hi all,
I'm trying to write an openthem controller for ESP32 without arduino libraries and in C (no CPP), and this sketch is really useful for my goal.
Reading a code, there is one thing that I cannot understand (99% for a lack of my knowledge).
When you want to send a bit (1 or 0) , the manchester encoding method is used: 
- Bit value '1' -> active-to-idle transition
- Bit value '0' -> idle-to-active transition.
But in the code seems that it is performed in the opposite way. 
- '1' -> OT_OUT_PIN changes from the initial state to LOW, stays on LOW state for 500 us, changes againg on HIGH state and finally stays in this state for other 500 us (so the transition is from LOW to HIGH)
- '0' -> OT_OUT_PIN changes from the initial state to HIGH, stays on HIGH state for 500 us, changes againg on LOW state and finally stays in this state for other 500 us (so the transition is from HIGH to LOW).
May you explain me or give me some suggestions for this issue?
Thank you in advance.

**Comment by ihormelnyk** [comment]
Hi @micBona ,
It depends on a schematic, in my case '1' on the controller output pin opens the transistor and sets the line to the low level.
That is why levels are inversed in the code.

**Comment by micBona** [comment]
Thank you for your prompt reply and for the information.
Now it is clear. I'll close the issue.
